// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mmWBramWriter_mmWBramWriter,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.338000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=218,HLS_SYN_LUT=428,HLS_VERSION=2020_2}" *)

module mmWBramWriter (
        ap_clk,
        ap_rst_n,
        buffer_in_address0,
        buffer_in_ce0,
        buffer_in_q0,
        buffer_out_address0,
        buffer_out_ce0,
        buffer_out_we0,
        buffer_out_d0,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_pp0_stage0 = 7'd2;
parameter    ap_ST_fsm_state4 = 7'd4;
parameter    ap_ST_fsm_state5 = 7'd8;
parameter    ap_ST_fsm_state6 = 7'd16;
parameter    ap_ST_fsm_state7 = 7'd32;
parameter    ap_ST_fsm_state8 = 7'd64;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [4:0] buffer_in_address0;
output   buffer_in_ce0;
input  [127:0] buffer_in_q0;
output  [7:0] buffer_out_address0;
output   buffer_out_ce0;
output   buffer_out_we0;
output  [31:0] buffer_out_d0;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg buffer_in_ce0;
reg[7:0] buffer_out_address0;
reg buffer_out_ce0;
reg buffer_out_we0;
reg[31:0] buffer_out_d0;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [4:0] buffer_r_address0;
reg    buffer_r_ce0;
wire   [28:0] buffer_r_q0;
reg   [5:0] i_2_reg_147;
reg   [31:0] n_points_1_reg_159;
wire   [5:0] add_ln29_fu_183_p2;
reg   [5:0] add_ln29_reg_312;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln29_fu_189_p2;
reg   [0:0] icmp_ln29_reg_317;
wire   [31:0] n_points_fu_226_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [31:0] add_ln55_fu_234_p2;
reg   [31:0] add_ln55_reg_331;
wire    ap_CS_fsm_state5;
wire   [7:0] shl_ln_fu_255_p3;
reg   [7:0] shl_ln_reg_339;
wire   [0:0] icmp_ln55_fu_245_p2;
reg   [28:0] lhs_V_reg_351;
wire    ap_CS_fsm_state6;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [5:0] ap_phi_mux_i_2_phi_fu_151_p4;
wire    ap_block_pp0_stage0;
reg   [31:0] i_reg_172;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state4;
wire   [63:0] i_2_cast_fu_195_p1;
wire   [63:0] zext_ln58_fu_269_p1;
wire   [63:0] zext_ln55_fu_240_p1;
wire   [63:0] zext_ln59_fu_279_p1;
wire   [63:0] zext_ln60_fu_289_p1;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln61_fu_307_p1;
wire   [31:0] zext_ln1348_fu_297_p1;
wire   [0:0] icmp_ln870_fu_200_p2;
wire   [0:0] icmp_ln31_fu_206_p2;
wire   [4:0] trunc_ln31_fu_218_p1;
wire   [0:0] and_ln31_fu_212_p2;
wire   [31:0] zext_ln31_fu_222_p1;
wire   [5:0] trunc_ln61_fu_251_p1;
wire   [7:0] or_ln58_fu_263_p2;
wire   [7:0] or_ln59_fu_274_p2;
wire   [7:0] or_ln60_fu_284_p2;
wire  signed [30:0] sext_ln1348_fu_294_p1;
wire   [7:0] add_ln61_fu_302_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

mmWBramWriter_buffer_r #(
    .DataWidth( 29 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buffer_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_r_address0),
    .ce0(buffer_r_ce0),
    .q0(buffer_r_q0)
);

mmWBramWriter_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_2_reg_147 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln29_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_2_reg_147 <= add_ln29_reg_312;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_172 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_reg_172 <= add_ln55_reg_331;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        n_points_1_reg_159 <= 32'd32;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln29_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        n_points_1_reg_159 <= n_points_fu_226_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln29_reg_312 <= add_ln29_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln55_reg_331 <= add_ln55_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln29_reg_317 <= icmp_ln29_fu_189_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        lhs_V_reg_351 <= buffer_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln55_fu_245_p2 == 1'd0))) begin
        shl_ln_reg_339[7 : 2] <= shl_ln_fu_255_p3[7 : 2];
    end
end

always @ (*) begin
    if ((icmp_ln29_fu_189_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln55_fu_245_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln29_reg_317 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_i_2_phi_fu_151_p4 = add_ln29_reg_312;
    end else begin
        ap_phi_mux_i_2_phi_fu_151_p4 = i_2_reg_147;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln55_fu_245_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_in_ce0 = 1'b1;
    end else begin
        buffer_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buffer_out_address0 = zext_ln61_fu_307_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buffer_out_address0 = zext_ln60_fu_289_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buffer_out_address0 = zext_ln59_fu_279_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buffer_out_address0 = zext_ln58_fu_269_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_out_address0 = 64'd0;
    end else begin
        buffer_out_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        buffer_out_ce0 = 1'b1;
    end else begin
        buffer_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buffer_out_d0 = zext_ln1348_fu_297_p1;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        buffer_out_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buffer_out_d0 = n_points_1_reg_159;
    end else begin
        buffer_out_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln55_fu_245_p2 == 1'd0)))) begin
        buffer_out_we0 = 1'b1;
    end else begin
        buffer_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buffer_r_ce0 = 1'b1;
    end else begin
        buffer_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln29_fu_189_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln29_fu_189_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln55_fu_245_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_fu_183_p2 = (ap_phi_mux_i_2_phi_fu_151_p4 + 6'd1);

assign add_ln55_fu_234_p2 = (i_reg_172 + 32'd1);

assign add_ln61_fu_302_p2 = (shl_ln_reg_339 + 8'd4);

assign and_ln31_fu_212_p2 = (icmp_ln870_fu_200_p2 & icmp_ln31_fu_206_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign buffer_in_address0 = i_2_cast_fu_195_p1;

assign buffer_r_address0 = zext_ln55_fu_240_p1;

assign i_2_cast_fu_195_p1 = ap_phi_mux_i_2_phi_fu_151_p4;

assign icmp_ln29_fu_189_p2 = ((ap_phi_mux_i_2_phi_fu_151_p4 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_206_p2 = ((n_points_1_reg_159 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_245_p2 = ((i_reg_172 == n_points_1_reg_159) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_200_p2 = ((buffer_in_q0 == 128'd0) ? 1'b1 : 1'b0);

assign n_points_fu_226_p3 = ((and_ln31_fu_212_p2[0:0] == 1'b1) ? zext_ln31_fu_222_p1 : n_points_1_reg_159);

assign or_ln58_fu_263_p2 = (shl_ln_fu_255_p3 | 8'd1);

assign or_ln59_fu_274_p2 = (shl_ln_reg_339 | 8'd2);

assign or_ln60_fu_284_p2 = (shl_ln_reg_339 | 8'd3);

assign sext_ln1348_fu_294_p1 = $signed(lhs_V_reg_351);

assign shl_ln_fu_255_p3 = {{trunc_ln61_fu_251_p1}, {2'd0}};

assign trunc_ln31_fu_218_p1 = i_2_reg_147[4:0];

assign trunc_ln61_fu_251_p1 = i_reg_172[5:0];

assign zext_ln1348_fu_297_p1 = $unsigned(sext_ln1348_fu_294_p1);

assign zext_ln31_fu_222_p1 = trunc_ln31_fu_218_p1;

assign zext_ln55_fu_240_p1 = i_reg_172;

assign zext_ln58_fu_269_p1 = or_ln58_fu_263_p2;

assign zext_ln59_fu_279_p1 = or_ln59_fu_274_p2;

assign zext_ln60_fu_289_p1 = or_ln60_fu_284_p2;

assign zext_ln61_fu_307_p1 = add_ln61_fu_302_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_339[1:0] <= 2'b00;
end

endmodule //mmWBramWriter
